apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  nodeName: ip-10-0-14-17 # <-- Cambiado para coincidir con la tesis
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    args: ['-s']
    ports:
    - containerPort: 5201