apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
spec:
  nodeName: ip-10-0-4-64 # <-- Cambiado para coincidir con la tesis
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    command: ['sleep', 'infinity']